server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery: #habilitar a descoberta de serviços registrados atraves do Eureka client, por exemplo
        locator: #habilitar a descoberta de serviços registrados atraves do Eureka client, por exemplo
          enabled: true #habilitar a descoberta de serviços registrados atraves do Eureka client, por exemplo
#          lower-case-service-id: true
      routes:
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**
      - id: api-gateway-docs
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#Pega o caminho que gera atualmente, e joga da parte de tras para a frente (reescreve)
  sleuth:
    sampler:
      probability: 1.0 #Configurado para rastrear 100% da aplicação, em produção remcomenda-se rastrear 5%