server:
  port: 8888
spring:
  application:
    name: schulz-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Markosbn/schulz-config-server.git
          #username:
          #password:
          default-label: master #branch
          search-paths:         #pasta a pegar dados
            - 'greeting-service*'