server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10 #configura o maximo de concorrencias simultaneas
  ratelimiter:
    instances:
      default:
        limit-for-period: 2 #limite de requisições por tempo
        limit-refresh-period: 10s #tempo total do limite de requisições
  retry:
    instances:
      default: #NOME DA INSTANCIA DEFINIDO AQUI
        max-attempts: 5 #QUANTIDADE DE TENTATIVAS DEFINIDAS AQUI
        wait-duration: 1s #configura o tempo que leva para cada retry
        enable-exponential-backoff: true #Configura o tempo de cada retry como numeros de FIBONACCI
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: root
  sleuth:
    sampler:
      probability: 1.0 #Configurado para rastrear 100% da aplicação, em produção remcomenda-se rastrear 5%
#  zipkin:
#    base-url: http://localhost:9411/ #default configuration
springdoc:
  api-docs:
    path: book-service/v3/api-docs
  show-actuator: true