name: Continuous intergado with github

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build Eureka NamingServer Container image
        working-directory: ./dockerizando/07-naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build ApiGateway Container image
        working-directory: ./dockerizando/07-api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build cambio-service Microservice-jar
        working-directory: ./dockerizando/07-cambio-service
        run: mvn clean package -DskipTests
        
      - name: Build book-service Microservice-jar
        working-directory: ./dockerizando/07-book-service
        run: mvn clean package -DskipTests
        
      - name: Docker-compose Build
        working-directory: ./dockerizando
        run: docker-compose build
